export type Currency = {
  code: string;
  symbol: string;
  name: string;
};

export const currencyList: Currency[] = [
  { code: "USD", symbol: "$", name: "US Dollar" },
  { code: "EUR", symbol: "€", name: "Euro" },
  { code: "JPY", symbol: "¥", name: "Japanese Yen" },
  { code: "GBP", symbol: "£", name: "British Pound" },
  { code: "AUD", symbol: "A$", name: "Australian Dollar" },
  { code: "CAD", symbol: "C$", name: "Canadian Dollar" },
  { code: "CHF", symbol: "CHF", name: "Swiss Franc" },
  { code: "CNY", symbol: "¥", name: "Chinese Yuan" },
  { code: "SEK", symbol: "kr", name: "Swedish Krona" },
  { code: "NZD", symbol: "NZ$", name: "New Zealand Dollar" },
  { code: "MXN", symbol: "$", name: "Mexican Peso" },
  { code: "SGD", symbol: "S$", name: "Singapore Dollar" },
  { code: "HKD", symbol: "HK$", name: "Hong Kong Dollar" },
  { code: "NOK", symbol: "kr", name: "Norwegian Krone" },
  { code: "RUB", symbol: "₽", name: "Russian Ruble" },
  { code: "ZAR", symbol: "R", name: "South African Rand" },
  { code: "INR", symbol: "₹", name: "Indian Rupee" },
  { code: "BRL", symbol: "R$", name: "Brazilian Real" },
  { code: "IDR", symbol: "Rp", name: "Indonesian Rupiah" },
  { code: "THB", symbol: "฿", name: "Thai Baht" },
  { code: "PLN", symbol: "zł", name: "Polish Zloty" },
  { code: "TRY", symbol: "₺", name: "Turkish Lira" },
  { code: "PHP", symbol: "₱", name: "Philippine Peso" },
  { code: "AED", symbol: "د.إ", name: "United Arab Emirates Dirham" },
  { code: "MYR", symbol: "RM", name: "Malaysian Ringgit" },
  { code: "CZK", symbol: "Kč", name: "Czech Koruna" },
  { code: "HUF", symbol: "Ft", name: "Hungarian Forint" },
  { code: "ILS", symbol: "₪", name: "Israeli New Shekel" },
  { code: "VND", symbol: "₫", name: "Vietnamese Dong" },
  { code: "PKR", symbol: "₨", name: "Pakistani Rupee" },
  { code: "COP", symbol: "$", name: "Colombian Peso" },
  { code: "DOP", symbol: "RD$", name: "Dominican Peso" },
  { code: "ARS", symbol: "$", name: "Argentine Peso" },
  { code: "NGN", symbol: "₦", name: "Nigerian Naira" },
  { code: "LKR", symbol: "Rs", name: "Sri Lankan Rupee" },
  { code: "MAD", symbol: "د.م.", name: "Moroccan Dirham" },
  { code: "RSD", symbol: "дин.", name: "Serbian Dinar" },
  { code: "QAR", symbol: "ر.ق", name: "Qatari Rial" },
  { code: "TWD", symbol: "NT$", name: "New Taiwan Dollar" },
  { code: "XOF", symbol: "CFA", name: "West African CFA Franc" },
  { code: "XAF", symbol: "CFA", name: "Central African CFA Franc" },
  { code: "FJD", symbol: "FJ$", name: "Fijian Dollar" },
  { code: "BBD", symbol: "Bds$", name: "Barbadian Dollar" },
  { code: "JMD", symbol: "J$", name: "Jamaican Dollar" },
  { code: "BND", symbol: "B$", name: "Brunei Dollar" },
  { code: "XCD", symbol: "$", name: "East Caribbean Dollar" },
  { code: "RWF", symbol: "FRw", name: "Rwandan Franc" },
  { code: "TZS", symbol: "TSh", name: "Tanzanian Shilling" },
  { code: "GHS", symbol: "₵", name: "Ghanaian Cedi" },
  { code: "SYP", symbol: "£", name: "Syrian Pound" },
  { code: "KZT", symbol: "₸", name: "Kazakhstani Tenge" },
  { code: "MDL", symbol: "lei", name: "Moldovan Leu" },
  { code: "BYN", symbol: "Br", name: "Belarusian Ruble" },
  { code: "MMK", symbol: "K", name: "Myanmar Kyat" },
  { code: "MOP", symbol: "MOP$", name: "Macanese Pataca" },
  { code: "BGN", symbol: "лв", name: "Bulgarian Lev" },
  { code: "KWD", symbol: "د.ك", name: "Kuwaiti Dinar" },
  { code: "OMR", symbol: "ر.ع.", name: "Omani Rial" },
  { code: "JOD", symbol: "د.أ", name: "Jordanian Dinar" },
  { code: "BAM", symbol: "KM", name: "Bosnia-Herzegovina Convertible Mark" },
  { code: "HRK", symbol: "kn", name: "Croatian Kuna" },
  { code: "SLL", symbol: "Le", name: "Sierra Leonean Leone" },
  { code: "SCR", symbol: "₨", name: "Seychellois Rupee" },
  { code: "TZS", symbol: "TSh", name: "Tanzanian Shilling" },
  { code: "GEL", symbol: "₾", name: "Georgian Lari" },
  { code: "STN", symbol: "Db", name: "São Tomé and Príncipe Dobra" },
  { code: "AWG", symbol: "Afl.", name: "Aruban Florin" },
  { code: "KID", symbol: "A$", name: "Kiribati Dollar" },
  { code: "AUD", symbol: "A$", name: "Australian Dollar" },
  { code: "FJD", symbol: "FJ$", name: "Fijian Dollar" },
  { code: "PGK", symbol: "K", name: "Papua New Guinean Kina" },
  { code: "XPF", symbol: "₣", name: "CFP Franc" },
  { code: "MGA", symbol: "Ar", name: "Malagasy Ariary" },
  { code: "ERN", symbol: "Nkf", name: "Eritrean Nakfa" },
  { code: "TMT", symbol: "m", name: "Turkmenistani Manat" },
  { code: "NIO", symbol: "C$", name: "Nicaraguan Córdoba" },
  { code: "CUP", symbol: "$", name: "Cuban Peso" },
  { code: "PEN", symbol: "S/", name: "Peruvian Sol" },
  { code: "PAB", symbol: "B/.", name: "Panamanian Balboa" },
  { code: "HNL", symbol: "L", name: "Honduran Lempira" },
  { code: "GMD", symbol: "D", name: "Gambian Dalasi" },
  { code: "KPW", symbol: "₩", name: "North Korean Won" },
  { code: "KRW", symbol: "₩", name: "South Korean Won" },
  { code: "LTL", symbol: "Lt", name: "Lithuanian Litas" },
  { code: "LVL", symbol: "Ls", name: "Latvian Lats" },
];

export const getUserCurrency = () => {
  const locale = navigator.language || "en-US";
  const region = locale.split("-")[1]?.toUpperCase() || "";
  const regionToCurrencyMap: { [key: string]: string } = {
    US: "USD",
    GB: "GBP",
    FR: "EUR",
    DE: "EUR",
    ES: "EUR",
    CN: "CNY",
    IN: "INR",
    AU: "AUD",
    CA: "CAD",
    BR: "BRL",
    MX: "MXN",
    NZ: "NZD",
    RU: "RUB",
    ZA: "ZAR",
    SE: "SEK",
    CH: "CHF",
    SG: "SGD",
    HK: "HKD",
    KR: "KRW",
    JP: "JPY",
    PT: "EUR",
    IT: "EUR",
    IE: "EUR",
    DK: "DKK",
    NO: "NOK",
    FI: "EUR",
    GR: "EUR",
    TR: "TRY",
    AE: "AED",
    NG: "NGN",
    PH: "PHP",
    TZ: "TZS",
    GH: "GHS",
    CL: "CLP",
    VE: "VES",
    AR: "ARS",
    CO: "COP",
    CR: "CRC",
    DO: "DOP",
    HT: "HTG",
    PY: "PYG",
    BO: "BOB",
    UY: "UYU",
    PE: "PEN",
    SV: "USD",
    JM: "JMD",
    TT: "TTD",
    BS: "BSD",
    BZ: "BZD",
    KY: "KYD",
    LC: "XCD",
    VC: "XCD",
    DM: "XCD",
    SX: "ANG",
    GP: "EUR",
    MQ: "EUR",
    RE: "EUR",
    YT: "EUR",
    WF: "XPF",
    PF: "XPF",
    MH: "USD",
    PW: "USD",
    KI: "AUD",
    NR: "AUD",
    TV: "AUD",
    VU: "VUV",
    NC: "XPF",
    TK: "AUD",
    GU: "USD",
    MP: "USD",
    PR: "USD",
    VI: "USD",
    AS: "USD",
    FM: "USD",
    AO: "AOA",
    MA: "MAD",
    DZ: "DZD",
    TN: "TND",
    EG: "EGP",
    LY: "LYD",
    IQ: "IQD",
    JO: "JOD",
    PK: "PKR",
    IR: "IRR",
    KZ: "KZT",
    UA: "UAH",
  };
  return regionToCurrencyMap[region] || "USD";
};
