// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	AUTH_GOOGLE_ID: string;
	AUTH_GOOGLE_SECRET: string;
	NEXTAUTH_URL: string;
	AUTH_SECRET: string;
	DB: D1Database;
}
